run:
  timeout: 3m
linters:
  enable:
    - megacheck
    - govet
    - revive
    - gocyclo
    - gosec
    - unconvert
    - dupl
    - nakedret
    - prealloc
    - exportloopref
    - gocritic
    - whitespace
    - misspell
    - depguard
    - importas
    - contextcheck
    - nolintlint
    - revive
