version: '3'

services:
  api:
    build: .
    command: api
    depends_on:
    - postgres
  postgres:
    image: postgres:${POSTGRES_TAG:-latest}
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: geocloud
      POSTGRES_USER: geocloud
      POSTGRES_PASSWORD: pwd
  worker:
    build: .
    command: worker
    depends_on:
    - postgres
    - registry-mirror
  registry-mirror:
    image: registry:${REGISTRY_TAG:-2}
    ports:
    - 5000:5000
    volumes:
    - ./registry-mirror/config.yml:/etc/docker/registry/config.yml:ro
