version: '3.4'

networks:
  api:
  migrate:
  worker:
  secretary:

services:
  api:
    build: .
    image: &image ghcr.io/logsquaredn/rototiller:${ROTOTILLER_TAG:-latest}
    command: a
    volumes: [~/.aws/:/root/.aws/:ro]
    networks: [api]
    ports: [8080:8080]
    depends_on: &depends_on [datastore, messagequeue, migrate, objectstore]
    environment: &environment
      ROTOTILLER_POSTGRES_ADDRESS: datastore
      ROTOTILLER_POSTGRES_PASSWORD: rototiller
      ROTOTILLER_S3_BUCKET: rototiller
      ROTOTILLER_S3_ENDPOINT: http://objectstore:9000
      ROTOTILLER_S3_DISABLE_SSL: t
      ROTOTILLER_S3_FORCE_PATH_STYLE: t
      ROTOTILLER_AMQP_ADDRESS: messagequeue
      ROTOTILLER_AMQP_PASSWORD: rototiller
      ROTOTILLER_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-rototiller}
      ROTOTILLER_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-rototiller}
      ROTOTILLER_STRIPE_API_KEY: ${ROTOTILLER_STRIPE_API_KEY}
  migrate:
    build: .
    image: *image
    command: m
    networks: [migrate]
    depends_on: [datastore]
    environment: *environment
  secretary:
    build: .
    image: *image
    command: s --work-jobs-before 1s --work-storage-before 1s
    volumes: [~/.aws/:/root/.aws/:ro]
    networks: [secretary]
    depends_on: [datastore, objectstore]
    environment:
      <<: *environment
      ROTOTILLER_S3_ARCHIVE_BUCKET: rototiller-archive
      ROTOTILLER_S3_ARCHIVE_ENDPOINT: http://objectstore:9000
      ROTOTILLER_S3_ARCHIVE_DISABLE_SSL: t
      ROTOTILLER_S3_ARCHIVE_FORCE_PATH_STYLE: t
  objectstore:
    image: minio/minio:${MINIO_TAG:-latest}
    command: server /var/lib/minio --console-address ":9001"
    volumes: [./hack/minio:/var/lib/minio:z]
    networks: [api, worker, secretary]
    ports: [9000:9000, 9001:9001]
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-rototiller}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-rototiller}
  datastore:
    image: postgres:${POSTGRES_TAG:-alpine}
    networks: [api, migrate, worker, secretary]
    ports: [5432:5432]
    volumes: [./hack/postgresql:/var/lib/postgresql]
    environment:
      POSTGRES_DB: rototiller
      POSTGRES_USER: rototiller
      POSTGRES_PASSWORD: rototiller
  messagequeue:
    image: rabbitmq:${RABBITMQ_TAG:-alpine}
    networks: [api, worker]
    ports: [5672:5672, 15672:15672]
    privileged: true
    volumes: [./hack/rabbitmq/lib:/var/lib/rabbitmq:z, ./hack/rabbitmq/etc:/etc/rabbitmq:ro]
  worker:
    build: .
    image: *image
    command: w
    volumes: [~/.aws:/root/.aws:ro, ./hack/rototiller:/var/lib/rototiller:z]
    networks: [worker]
    depends_on: *depends_on
    environment: *environment
  removebadgeometry:
    build: .
    image: *image
    volumes: [./testdata/geojson/featurecollection.json:/tmp/input/input.json:ro]
    entrypoint: removebadgeometry
  buffer:
    build: .
    image: *image
    volumes: [./testdata/geojson/featurecollection.json:/tmp/input/input.json:ro]
    entrypoint: buffer
  filter:
    build: .
    image: *image
    volumes: [./testdata/geojson/featurecollection.json:/tmp/input/input.json:ro]
    entrypoint: filter
  reproject:
    build: .
    image: *image
    volumes: [./testdata/geojson/featurecollection.json:/tmp/input/input.json:ro]
    entrypoint: reproject
  vectorlookup:
    build: .
    image: *image
    volumes: [./testdata/geojson/featurecollection.json:/tmp/input/input.json:ro]
    entrypoint: vectorlookup
  rasterlookup:
    build: .
    image: *image
    volumes: [./testdata/raster/input.tif:/tmp/input/input.tif:ro]
    entrypoint: rasterlookup
