version: '3.4'

services:
  migrate:
    image: &rototiller_image ghcr.io/logsquaredn/rototiller:${ROTOTILLER_TAG:-latest}
    build: .
    command: migrate --postgres-addr=postgres://rototiller:rototiller@postgres:5432?sslmode=disable
    depends_on: &rototiller_depends_on [postgres, rabbitmq]
  api:
    image: *rototiller_image
    build: .
    command: api --amqp-addr=amqp://rototiller:rototiller@rabbitmq:5672 --postgres-addr=postgres://rototiller:rototiller@postgres:5432?sslmode=disable --bucket-addr=file:///var/lib/rototiller/blobstore
    ports: [8080:8080]
    volumes: [./hack/rototiller/blobstore:/var/lib/rototiller/blobstore]
    depends_on: *rototiller_depends_on
  worker: &worker_service
    image: *rototiller_image
    build: .
    command: worker --amqp-addr=amqp://rototiller:rototiller@rabbitmq:5672 --postgres-addr=postgres://rototiller:rototiller@postgres:5432?sslmode=disable --bucket-addr=file:///var/lib/rototiller/blobstore
    volumes: [./hack/rototiller/blobstore:/var/lib/rototiller/blobstore, ./hack/rototiller/workingdir:/var/lib/rototiller/workingdir]
    depends_on: *rototiller_depends_on
  worker-alt: *worker_service
  secretary:
    image: &rototiller_image ghcr.io/logsquaredn/rototiller:${ROTOTILLER_TAG:-latest}
    build: .
    command: secretary --postgres-addr=postgres://rototiller:rototiller@postgres:5432?sslmode=disable
    depends_on: *rototiller_depends_on
  postgres:
    image: postgres:${POSTGRES_TAG:-alpine}
    ports: [5432:5432]
    volumes: [./hack/postgresql:/var/lib/postgresql]
    environment:
      POSTGRES_DB: rototiller
      POSTGRES_USER: rototiller
      POSTGRES_PASSWORD: rototiller
  rabbitmq:
    image: rabbitmq:${RABBITMQ_TAG:-alpine}
    privileged: true
    ports: [5672:5672, 15672:15672]
    volumes: [./hack/rabbitmq/lib:/var/lib/rabbitmq:z, ./hack/rabbitmq/etc:/etc/rabbitmq:ro]
