version: '3.4'

services:
  api:
    build: { context: ., target: api }
    command: --postgres-host=postgres --postgres-password=pwd
    depends_on: [postgres]
    networks: [api]
    ports: [8080:8080]
  postgres:
    image: postgres:${POSTGRES_TAG:-latest}
    ports: [5432:5432]
    volumes: [./postgres/:/docker-entrypoint-initdb.d/:ro]
    networks: [api]
    environment:
      POSTGRES_DB: geocloud
      POSTGRES_USER: geocloud
      POSTGRES_PASSWORD: pwd
  worker:
    build: { context: ., target: worker }
    privileged: true
    command: --postgres-host=postgres --postgres-password=pwd
    networks: [worker]
    depends_on: [postgres] # , registry]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  # registry:
  #   image: registry:${REGISTRY_TAG:-2}
  #   ports: [5000:5000]
  #   volumes: [registry/config.yml:/etc/docker/registry/config.yml:ro]
  #   networks: [worker]

networks:
  api:
  worker:
