[package]
name = "janitor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = { version = "0.7.5", features = ["with-chrono-0_4"] }
chrono = "0.4.19"
rust-s3 = "0.30.0"
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["full"] }
clap = "3.1.12"