version: '3.4'

services:
  removebadgeometry:
    build:
      context: .
      target: removebadgeometry
    image: logsquaredn/geocloud:task-remove-bad-geometry
    volumes: [../testdata/geojson/featurecollection.geojson:/job/1/input/input.geojson:ro]
    command: /job/1/input/input.geojson /tmp
  buffer:
    build:
      context: .
      target: buffer
    image: logsquaredn/geocloud:task-buffer
    volumes: [../testdata/geojson/featurecollection.geojson:/job/1/input/input.geojson:ro]
    command: /job/1/input/input.geojson /tmp 2
  filter:
    build:
      context: .
      target: filter
    image: logsquaredn/geocloud:task-filter
    volumes: [../testdata/geojson/featurecollection.geojson:/job/1/input/input.geojson:ro]
    command: /job/1/input/input.geojson /tmp prop0 value0
  reproject:
    build:
      context: .
      target: reproject
    image: logsquaredn/geocloud:task-reproject
    volumes: [../testdata/geojson/featurecollection.geojson:/job/1/input/input.geojson:ro]
    command: /job/1/input/input.geojson /tmp 2000
