// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/storage/v1/storage.proto

package storagev1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/logsquaredn/geocloud/api/storage/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// StorageServiceName is the fully-qualified name of the StorageService service.
	StorageServiceName = "api.storage.v1.StorageService"
)

// StorageServiceClient is a client for the api.storage.v1.StorageService service.
type StorageServiceClient interface {
	GetStorage(context.Context, *connect_go.Request[v1.GetStorageRequest]) (*connect_go.ServerStreamForClient[v1.GetStorageResponse], error)
	CreateStorage(context.Context) *connect_go.ClientStreamForClient[v1.CreateStorageRequest, v1.CreateStorageResponse]
}

// NewStorageServiceClient constructs a client for the api.storage.v1.StorageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStorageServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) StorageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &storageServiceClient{
		getStorage: connect_go.NewClient[v1.GetStorageRequest, v1.GetStorageResponse](
			httpClient,
			baseURL+"/api.storage.v1.StorageService/GetStorage",
			opts...,
		),
		createStorage: connect_go.NewClient[v1.CreateStorageRequest, v1.CreateStorageResponse](
			httpClient,
			baseURL+"/api.storage.v1.StorageService/CreateStorage",
			opts...,
		),
	}
}

// storageServiceClient implements StorageServiceClient.
type storageServiceClient struct {
	getStorage    *connect_go.Client[v1.GetStorageRequest, v1.GetStorageResponse]
	createStorage *connect_go.Client[v1.CreateStorageRequest, v1.CreateStorageResponse]
}

// GetStorage calls api.storage.v1.StorageService.GetStorage.
func (c *storageServiceClient) GetStorage(ctx context.Context, req *connect_go.Request[v1.GetStorageRequest]) (*connect_go.ServerStreamForClient[v1.GetStorageResponse], error) {
	return c.getStorage.CallServerStream(ctx, req)
}

// CreateStorage calls api.storage.v1.StorageService.CreateStorage.
func (c *storageServiceClient) CreateStorage(ctx context.Context) *connect_go.ClientStreamForClient[v1.CreateStorageRequest, v1.CreateStorageResponse] {
	return c.createStorage.CallClientStream(ctx)
}

// StorageServiceHandler is an implementation of the api.storage.v1.StorageService service.
type StorageServiceHandler interface {
	GetStorage(context.Context, *connect_go.Request[v1.GetStorageRequest], *connect_go.ServerStream[v1.GetStorageResponse]) error
	CreateStorage(context.Context, *connect_go.ClientStream[v1.CreateStorageRequest]) (*connect_go.Response[v1.CreateStorageResponse], error)
}

// NewStorageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStorageServiceHandler(svc StorageServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/api.storage.v1.StorageService/GetStorage", connect_go.NewServerStreamHandler(
		"/api.storage.v1.StorageService/GetStorage",
		svc.GetStorage,
		opts...,
	))
	mux.Handle("/api.storage.v1.StorageService/CreateStorage", connect_go.NewClientStreamHandler(
		"/api.storage.v1.StorageService/CreateStorage",
		svc.CreateStorage,
		opts...,
	))
	return "/api.storage.v1.StorageService/", mux
}

// UnimplementedStorageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStorageServiceHandler struct{}

func (UnimplementedStorageServiceHandler) GetStorage(context.Context, *connect_go.Request[v1.GetStorageRequest], *connect_go.ServerStream[v1.GetStorageResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.storage.v1.StorageService.GetStorage is not implemented"))
}

func (UnimplementedStorageServiceHandler) CreateStorage(context.Context, *connect_go.ClientStream[v1.CreateStorageRequest]) (*connect_go.Response[v1.CreateStorageResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("api.storage.v1.StorageService.CreateStorage is not implemented"))
}
