resources:
- name: containerd
  type: github-release
  icon: package-variant-closed
  check_every: never
  source:
    owner: containerd
    repository: containerd
- name: gdal-latest
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: osgeo/gdal
    tag: latest
- name: geocloud
  type: git
  icon: github
  source:
    uri: git@github.com:logsquaredn/geocloud.git
    branch: ((branch))
    private_key: ((geocloud_private_key))
- name: geocloud-latest
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: logsquaredn/geocloud
    tag: latest
- name: golang-latest
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: golang
    tag: latest
- name: oci-build-task
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: vito/oci-build-task
- name: runc
  type: github-release
  icon: package-variant-closed
  check_every: never
  source:
    owner: opencontainers
    repository: runc
- name: ubuntu-bionic
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: ubuntu
    tag: bionic
jobs:
- name: build-geocloud
  serial: true
  plan:
  - in_parallel:
    - get: containerd
      params:
        globs: [containerd-*-linux-amd64.tar.gz]
    - get: geocloud
      trigger: true
    - get: golang-latest
      params:
        format: oci
    - get: oci-build-task
    - get: runc
      params:
        globs: [runc.amd64]
    - get: ubuntu-bionic
      params:
        format: oci
  - load_var: containerd_version
    file: containerd/version
  - task: check-releases
    config:
      image_resource:
        type: registry-image
        source:
          username: ((docker_username))
          password: ((docker_password))
          repository: alpine
      platform: linux
      inputs:
      - name: containerd
      - name: runc
      run:
        path: sh
        args:
        - -ce
        - |
          echo "containerd_version: $(cat containerd/version)"
          ls containerd/
          ls runc/
  - task: build-geocloud
    image: oci-build-task
    privileged: true
    config:
      platform: linux
      inputs:
      - name: containerd
      - name: geocloud
      - name: golang-latest
      - name: runc
      - name: ubuntu-bionic
      outputs:
      - name: image
      params:
        CONTEXT: geocloud
        IMAGE_ARG_base_image: ubuntu-bionic/image.tar
        IMAGE_ARG_build_image: golang-latest/image.tar
        BUILD_ARG_containerd_release: assets/containerd.tgz
        BUILD_ARG_runc_release: assets/runc
      run:
        path: sh
        args:
        - -ce
        - |
          cp containerd/containerd-((.:containerd_version))-linux-amd64.tar.gz geocloud/assets/containerd.tgz
          cp runc/runc.amd64 geocloud/assets/runc
          build
  - put: geocloud-latest
    params:
      image: image/image.tar
    get_params:
      skip_download: true
- name: build-tasks
  serial: true
  plan:
  - in_parallel:
    - get: geocloud
      trigger: true
    - get: gdal-latest
      params:
        format: oci
    - get: oci-build-task
  - in_parallel:
    - across:
      - var: task
        values: [
          buffer,
          filter,
          reproject,
        ]
      task: build-task-with-identically-named-task-folder
      image: oci-build-task
      privileged: true
      config:
        platform: linux
        inputs:
        - name: geocloud
        - name: gdal-latest
        outputs:
        - name: image
        params:
          CONTEXT: geocloud/tasks
          IMAGE_ARG_base_image: gdal-latest/image.tar
          IMAGE_ARG_build_image: gdal-latest/image.tar
          BUILD_ARG_task: ((.:task))
        run:
          path: build
    - task: build-task-with-differently-named-task-folder
      image: oci-build-task
      privileged: true
      config:
        platform: linux
        inputs:
        - name: geocloud
        - name: gdal-latest
        outputs:
        - name: image
        params:
          CONTEXT: geocloud/tasks
          IMAGE_ARG_base_image: gdal-latest/image.tar
          IMAGE_ARG_build_image: gdal-latest/image.tar
          BUILD_ARG_task: removeBadGeometry
          BUILD_ARG_task_folder: badGeometry
        run:
          path: build
