resources:
- name: containerd
  type: github-release
  icon: package-variant-closed
  source:
    owner: containerd
    repository: containerd
- name: gdal-latest
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: osgeo/gdal
    tag: latest
- name: geocloud
  type: git
  icon: github
  source:
    uri: git@github.com:logsquaredn/geocloud.git
    branch: ((branch))
    private_key: ((geocloud_private_key))
- name: geocloud-latest
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: logsquaredn/geocloud
    tag: latest
- name: golang-latest
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: golang
    tag: latest
- name: oci-build-task
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: vito/oci-build-task
- name: runc
  type: github-release
  icon: package-variant-closed
  source:
    owner: opencontainers
    repository: runc
- name: ubuntu-bionic
  type: registry-image
  icon: docker
  source:
    username: ((docker_username))
    password: ((docker_password))
    repository: ubuntu
    tag: bionic
jobs:
- name: build-geocloud
  serial: true
  plan:
  - in_parallel:
    - get: containerd
      params:
        globs: [runc.amd64]
    - get: geocloud
      trigger: true
    - get: golang-latest
      params:
        format: oci
    - get: oci-build-task
    - get: runc
      params:
        globs: []
    - get: ubuntu-bionic
      params:
        format: oci
  - load_var: containerd_version
    file: containerd/version
  - task: build-geocloud
    image: oci-build-task
    privileged: true
    config:
      platform: linux
      inputs:
      - name: containerd
      - name: geocloud
      - name: golang-latest
      - name: runc
      - name: ubuntu-bionic
      outputs:
      - name: image
      params:
        CONTEXT: geocloud
        IMAGE_ARG_base_image: ubuntu-bionic/image.tar
        IMAGE_ARG_build_image: golang-latest/image.tar
        BUILD_ARG_containerd_release: containerd/containerd-((.:containerd_version))-linux-amd64.tar.gz
        BUILD_ARG_runc_release: runc/runc.amd64
      run:
        path: build
  - put: geocloud-latest
    params:
      image: image/image.tar
    get_params:
      skip_download: true
- name: build-tasks
  serial: true
  plan:
  - in_parallel:
    - get: geocloud
      trigger: true
    - get: gdal-latest
      params:
        format: oci
    - get: oci-build-task
  - across:
    - var: task
      values: [
        badGeometry,
        buffer,
        filter,
        reproject,
      ]
    task: build-geocloud
    image: oci-build-task
    privileged: true
    config:
      platform: linux
      inputs:
      - name: geocloud
      - name: gdal-latest
      outputs:
      - name: image
      params:
        CONTEXT: geocloud/tasks
        IMAGE_ARG_base_image: gdal-latest/image.tar
        IMAGE_ARG_build_image: gdal-latest/image.tar
        BUILD_ARG_task: ((.:task))
      run:
        path: build
