// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/api/storage.proto

package apiconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	api "github.com/logsquaredn/rototiller/pkg/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// StorageServiceName is the fully-qualified name of the StorageService service.
	StorageServiceName = "rototiller.api.StorageService"
)

// StorageServiceClient is a client for the rototiller.api.StorageService service.
type StorageServiceClient interface {
	GetStorageContent(context.Context, *connect_go.Request[api.GetStorageContentRequest]) (*connect_go.ServerStreamForClient[api.GetStorageContentResponse], error)
	GetStorage(context.Context, *connect_go.Request[api.GetStorageRequest]) (*connect_go.Response[api.GetStorageResponse], error)
	CreateStorage(context.Context) *connect_go.ClientStreamForClient[api.CreateStorageRequest, api.CreateStorageResponse]
}

// NewStorageServiceClient constructs a client for the rototiller.api.StorageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStorageServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) StorageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &storageServiceClient{
		getStorageContent: connect_go.NewClient[api.GetStorageContentRequest, api.GetStorageContentResponse](
			httpClient,
			baseURL+"/rototiller.api.StorageService/GetStorageContent",
			opts...,
		),
		getStorage: connect_go.NewClient[api.GetStorageRequest, api.GetStorageResponse](
			httpClient,
			baseURL+"/rototiller.api.StorageService/GetStorage",
			opts...,
		),
		createStorage: connect_go.NewClient[api.CreateStorageRequest, api.CreateStorageResponse](
			httpClient,
			baseURL+"/rototiller.api.StorageService/CreateStorage",
			opts...,
		),
	}
}

// storageServiceClient implements StorageServiceClient.
type storageServiceClient struct {
	getStorageContent *connect_go.Client[api.GetStorageContentRequest, api.GetStorageContentResponse]
	getStorage        *connect_go.Client[api.GetStorageRequest, api.GetStorageResponse]
	createStorage     *connect_go.Client[api.CreateStorageRequest, api.CreateStorageResponse]
}

// GetStorageContent calls rototiller.api.StorageService.GetStorageContent.
func (c *storageServiceClient) GetStorageContent(ctx context.Context, req *connect_go.Request[api.GetStorageContentRequest]) (*connect_go.ServerStreamForClient[api.GetStorageContentResponse], error) {
	return c.getStorageContent.CallServerStream(ctx, req)
}

// GetStorage calls rototiller.api.StorageService.GetStorage.
func (c *storageServiceClient) GetStorage(ctx context.Context, req *connect_go.Request[api.GetStorageRequest]) (*connect_go.Response[api.GetStorageResponse], error) {
	return c.getStorage.CallUnary(ctx, req)
}

// CreateStorage calls rototiller.api.StorageService.CreateStorage.
func (c *storageServiceClient) CreateStorage(ctx context.Context) *connect_go.ClientStreamForClient[api.CreateStorageRequest, api.CreateStorageResponse] {
	return c.createStorage.CallClientStream(ctx)
}

// StorageServiceHandler is an implementation of the rototiller.api.StorageService service.
type StorageServiceHandler interface {
	GetStorageContent(context.Context, *connect_go.Request[api.GetStorageContentRequest], *connect_go.ServerStream[api.GetStorageContentResponse]) error
	GetStorage(context.Context, *connect_go.Request[api.GetStorageRequest]) (*connect_go.Response[api.GetStorageResponse], error)
	CreateStorage(context.Context, *connect_go.ClientStream[api.CreateStorageRequest]) (*connect_go.Response[api.CreateStorageResponse], error)
}

// NewStorageServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStorageServiceHandler(svc StorageServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/rototiller.api.StorageService/GetStorageContent", connect_go.NewServerStreamHandler(
		"/rototiller.api.StorageService/GetStorageContent",
		svc.GetStorageContent,
		opts...,
	))
	mux.Handle("/rototiller.api.StorageService/GetStorage", connect_go.NewUnaryHandler(
		"/rototiller.api.StorageService/GetStorage",
		svc.GetStorage,
		opts...,
	))
	mux.Handle("/rototiller.api.StorageService/CreateStorage", connect_go.NewClientStreamHandler(
		"/rototiller.api.StorageService/CreateStorage",
		svc.CreateStorage,
		opts...,
	))
	return "/rototiller.api.StorageService/", mux
}

// UnimplementedStorageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStorageServiceHandler struct{}

func (UnimplementedStorageServiceHandler) GetStorageContent(context.Context, *connect_go.Request[api.GetStorageContentRequest], *connect_go.ServerStream[api.GetStorageContentResponse]) error {
	return connect_go.NewError(connect_go.CodeUnimplemented, errors.New("rototiller.api.StorageService.GetStorageContent is not implemented"))
}

func (UnimplementedStorageServiceHandler) GetStorage(context.Context, *connect_go.Request[api.GetStorageRequest]) (*connect_go.Response[api.GetStorageResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("rototiller.api.StorageService.GetStorage is not implemented"))
}

func (UnimplementedStorageServiceHandler) CreateStorage(context.Context, *connect_go.ClientStream[api.CreateStorageRequest]) (*connect_go.Response[api.CreateStorageResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("rototiller.api.StorageService.CreateStorage is not implemented"))
}
