definitions:
  geocloud.CreateResponse:
    properties:
      id:
        type: string
    type: object
  geocloud.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  geocloud.StatusResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /create/buffer:
    post:
      consumes:
      - application/json
      - ' application/zip'
      description: |-
        <b><u>Create a buffer job</u></b>
        &emsp; - For extra info: https://gdal.org/api/vector_c_api.html#_CPPv412OGR_G_Buffer12OGRGeometryHdi
        &emsp; - Pass the geospatial data to be processed in the request body.
      parameters:
      - description: Buffer distance
        in: query
        name: distance
        required: true
        type: integer
      - description: Segment count
        in: query
        name: segmentCount
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geocloud.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
      summary: Create a buffer job
      tags:
      - createBuffer
  /create/filter:
    post:
      consumes:
      - application/json
      - ' application/zip'
      description: |-
        <b><u>Create a filter job</u></b>
        &emsp; - Pass the geospatial data to be processed in the request body.
      parameters:
      - description: Column to filter on
        in: query
        name: filterColumn
        required: true
        type: string
      - description: Value to filter on
        in: query
        name: filterValue
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geocloud.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
      summary: Create a filter job
      tags:
      - createFilter
  /create/removebadgeometry:
    post:
      consumes:
      - application/json
      - ' application/zip'
      description: |-
        <b><u>Create a remove bad geometry job</u></b>
        &emsp; - Pass the geospatial data to be processed in the request body.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geocloud.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
      summary: Create a remove bad geometry job
      tags:
      - createRemovebadgeometry
  /create/reproject:
    post:
      consumes:
      - application/json
      - ' application/zip'
      description: |-
        <b><u>Create a reproject job</u></b>
        &emsp; - Pass the geospatial data to be processed in the request body.
      parameters:
      - description: Target projection EPSG
        in: query
        name: targetProjection
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geocloud.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
      summary: Create a reproject job
      tags:
      - createReproject
  /create/vectorlookup:
    post:
      consumes:
      - application/json
      - ' application/zip'
      description: |-
        <b><u>Create a vector lookup job</u></b>
        &emsp; - Pass the geospatial data to be processed in the request body.
      parameters:
      - description: Longitude
        in: query
        name: longitude
        required: true
        type: number
      - description: Latitude
        in: query
        name: latitude
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geocloud.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
      summary: Create a vector lookup job
      tags:
      - createVectorlookup
  /result:
    get:
      description: Results are downloadable as geojson or zip. The zip will contain
        the files that comprise an ESRI shapefile.
      parameters:
      - description: Job ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      - ' application/zip'
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
      summary: Download geojson result of job
      tags:
      - result
  /status:
    get:
      parameters:
      - description: Job ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/geocloud.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/geocloud.ErrorResponse'
      summary: Get status of a job
      tags:
      - status
swagger: "2.0"
