version = 2
disabled_plugins = [
  "io.containerd.grpc.v1.cri",
  "io.containerd.snapshotter.v1.aufs",
  "io.containerd.snapshotter.v1.btrfs",
  "io.containerd.snapshotter.v1.devmapper",
  "io.containerd.snapshotter.v1.native",
  "io.containerd.snapshotter.v1.zfs"
]
subreaper = true
oom_score = -999

[metrics]
  address = "%s:%d"
