name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v3.1.0
  build-push:
    runs-on: ubuntu-latest
    steps:
      # - name: setup-qemu
      #   uses: docker/setup-qemu-action@v1
      - name: setup-buildx
        uses: docker/setup-buildx-action@v1
      - name: registry-login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-push
        id: build-push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=logsquaredn/geocloud:latest
          push: ${{ github.event_name == 'push' }}
          load: ${{ github.event_name != 'push' }}
          build-args: revision=${{ steps.get-tag.outputs.tag }}
          tags: logsquaredn/geocloud:${{ steps.get-tag.outputs.tag }}
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
      tag: ${{ steps.get-tag.outputs.tag }}
