name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: 
  contents: read
  packages: write 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v3.1.0
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: setup-qemu
      #   uses: docker/setup-qemu-action@v1
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      - name: registry-login
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get-tag
        id: get-tag
        run: echo "::set-output name=tag::${GITHUB_SHA::7}"
      - name: build-push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=ghcr.io/logsquaredn/geocloud:latest
          push: true
          build-args: revision=${{ steps.get-tag.outputs.tag }}
          tags: ghcr.io/logsquaredn/geocloud:${{ steps.get-tag.outputs.tag }}
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
      tag: ${{ steps.get-tag.outputs.tag }}
  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/logsquaredn/geocloud:${{ needs.build.outputs.tag }}@${{ needs.build.outputs.digest }}
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: version
        run: |
          geocloud -v
          docker -v
