name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: setup-qemu
      #   uses: docker/setup-qemu-action@v1
      - name: setup-buildx
        uses: docker/setup-buildx-action@v1
      - name: registry-login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build-buffer
        uses: docker/build-push-action@v2
        with:
          context: tasks/
          load: true
          target: buffer
          tags: logsquaredn/geocloud:task-buffer
      - name: build-filter
        uses: docker/build-push-action@v2
        with:
          context: tasks/
          load: true
          target: filter
          tags: logsquaredn/geocloud:task-filter
      - name: build-removebadgeometry
        uses: docker/build-push-action@v2
        with:
          context: tasks/
          load: true
          target: removebadgeometry
          tags: logsquaredn/geocloud:task-removebadgeometry
      - name: build-reproject
        uses: docker/build-push-action@v2
        with:
          context: tasks/
          load: true
          target: reproject
          tags: logsquaredn/geocloud:task-reproject
      - name: save-tasks
        run: docker save -o runtime/tasks.tar logsquaredn/geocloud:task-buffer logsquaredn/geocloud:task-filter logsquaredn/geocloud:task-removebadgeometry logsquaredn/geocloud:task-reproject
      - name: get-tag
        id: get-tag
        run: echo "::set-output name=tag::$(git rev-parse --short ${{ github.sha }})"
      - name: build-push
        id: build-push
        uses: docker/build-push-action@v2
        with:
          # cache-from: type=registry,ref=logsquaredn/geocloud:latest
          context: .
          push: ${{ github.event_name == 'push' }}
          build-args: |
            revision=${{ steps.get-tag.outputs.tag }}
          tags: logsquaredn/geocloud:${{ steps.get-tag.outputs.tag }}
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
      tag: ${{ steps.get-tag.outputs.tag }}
