name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: 
  contents: read
  packages: write 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: golangci/golangci-lint-action@v3.1.0
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: compose
        run: |
          make services sleep migrate detach
      - name: logs
        run: |
          sleep 11
          docker-compose logs api worker
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: setup-qemu
      #   uses: docker/setup-qemu-action@v1
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      - name: registry-login
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get-tag
        id: get-tag
        run: echo "::set-output name=tag::${GITHUB_SHA::7}"
      - uses: actions/checkout@v2
      - name: build
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/logsquaredn/geocloud:latest
          push: ${{ github.event_name == 'push' }}
          load: ${{ github.event_name != 'push' }}
          build-args: revision=${{ steps.get-tag.outputs.tag }}
          tags: ghcr.io/logsquaredn/geocloud:${{ steps.get-tag.outputs.tag }}
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      tag: ${{ steps.get-tag.outputs.tag }}
