name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # - name: setup-qemu
      #   uses: docker/setup-qemu-action@v1
      - name: setup-buildx
        uses: docker/setup-buildx-action@v1
      - name: registry-login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: save-tasks
        run: make save-tasks
      - name: get-tag
        id: get-tag
        run: echo "::set-output name=tag::$(git rev-parse --short ${{ github.sha }})"
      - name: debug
        run: |
          ls .
          ls runtime/
          echo "${{ steps.get-tag.outputs.tag }}"
      - name: build-push
        id: build-push
        uses: docker/build-push-action@v2
        with:
          # cache-from: type=registry,ref=logsquaredn/geocloud:latest
          context: .
          push: false # ${{ github.event_name == 'push' }}
          build-args: |
            revision=${{ steps.get-tag.outputs.tag }}
          tags: logsquaredn/geocloud:${{ steps.get-tag.outputs.tag }}
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
      tag: ${{ steps.get-tag.outputs.tag }}
