name: Release
on:
  push:
    tags:
      - '*'
permissions: 
  contents: read
  packages: write 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: setup-qemu
      #   uses: docker/setup-qemu-action@v1
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      - name: registry-login
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get-short-sha
        id: get-short-sha
        run: echo "::set-output name=short-sha::${GITHUB_SHA::7}"
      - name: get-tag
        id: get-tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"
      - uses: actions/checkout@v2
      - name: build
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/logsquaredn/geocloud:${{ steps.get-short-sha.outputs.short-sha }}
          push: true
          build-args: |
            version=${{ steps.get-tag.outputs.tag }}
            revision=${{ steps.get-short-sha.outputs.short-sha }}
          tags: |
            ghcr.io/logsquaredn/geocloud:${{ steps.get-tag.outputs.tag }}
            ghcr.io/logsquaredn/geocloud:latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      tag: ${{ steps.get-tag.outputs.tag }}
  release:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/logsquaredn/geocloud:${{ needs.build.outputs.tag }}@${{ needs.build.outputs.digest }}
      credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: create-release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ needs.build.outputs.tag }}
      - name: upload-geocloud
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/geocloud
          asset_name: geocloud_linux_amd64
          asset_content_type: application/octet-stream
      - name: upload-geocloudctl
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/geocloudctl
          asset_name: geocloudctl_linux_amd64
          asset_content_type: application/octet-stream
      - name: upload-task-removebadgeometry
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/removebadgeometry
          asset_name: task_removebadgeometry_linux_amd64
          asset_content_type: application/octet-stream
      - name: upload-task-filter
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/filter
          asset_name: task_filter_linux_amd64
          asset_content_type: application/octet-stream
      - name: upload-task-buffer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/buffer
          asset_name: task_buffer_linux_amd64
          asset_content_type: application/octet-stream
      - name: upload-task-reproject
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/reproject
          asset_name: task_reproject_linux_amd64
          asset_content_type: application/octet-stream
      - name: upload-task-vectorlookup
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/vectorlookup
          asset_name: task_vectorlookup_linux_amd64
          asset_content_type: application/octet-stream
      - name: upload-task-rasterlookup
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /usr/local/bin/rasterlookup
          asset_name: task_rasterlookup_linux_amd64
          asset_content_type: application/octet-stream
