name: Release
on:
  push:
    tags:
      - 'v*'
permissions: 
  contents: read
  packages: write 
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # - name: setup-qemu
      #   uses: docker/setup-qemu-action@v1
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      - name: registry-login
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get-short-sha
        id: get-short-sha
        run: echo "::set-output name=short-sha::${GITHUB_SHA::7}"
      - name: get-tag
        id: get-tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/v})"
      - uses: actions/checkout@v3
      - name: build
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ steps.get-short-sha.outputs.short-sha }}
          push: true
          build-args: |
            version=${{ steps.get-tag.outputs.tag }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get-tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      tag: ${{ steps.get-tag.outputs.tag }}
  release:
    runs-on: ubuntu-latest
    needs: push
    container:
      image: ghcr.io/${{ github.repository }}:${{ needs.push.outputs.tag }}@${{ needs.push.outputs.digest }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: get-version
        id: get-version
        run: echo "::set-output name=version::$(rototiller -v)"
      - name: create-release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ needs.push.outputs.tag }}
          body: |
            **Image**:   `ghcr.io/${{ github.repository }}:${{ needs.push.outputs.tag }}`
            **Digest**:  `${{ needs.push.outputs.digest }}`
            **Version**: `${{ steps.get-version.outputs.version }}`
